type AddOpenPositionCreated {
  company: Company!
}

type AddOpenPositionFailed {
  error: String!
  suggestion: String!
}

input AddOpenPositionInput {
  companyName: String!
  position: OpenPositionInput!
}

"""Union of possible outcomes when adding a position to a company"""
union AddOpenPositionResult = AddOpenPositionCreated | AddOpenPositionFailed

type Company {
  name: String!
  tagline: String!
  website: String!
  openPositions: [OpenPosition!]!
  technologies: [String!]!
}

type Mutation {
  """
  Add a new open positions for the given company. Example:
  ```
  mutation AgregarBusqueda {
    addOpenPosition(input: {
        companyName: "CompanyName", 
        position: {title: "Architect", url: "www.url.com"}
      }) {
      __typename  # Field to discriminate successfull results from failed ones
      ... on AddOpenPositionCreated {
        # The position was added successfully
        company {
          name
          openPositions {
            title
            url
          }
        }
      }
      ... on AddOpenPositionFailed {
        # There was an error adding the position
        error
        suggestion
      }
  
    }
  }
  ```
  """
  addOpenPosition(input: AddOpenPositionInput!): AddOpenPositionResult!
}

type OpenPosition {
  title: String!
  url: String!
  company: Company!
}

input OpenPositionInput {
  title: String!
  url: String!
}

input PeopleFilter {
  interestedIn: [String!]!
  openToJobOffers: Boolean!
  seniority: Seniority!
}

interface Person {
  name: String!
  email: String!
  interests: [String!]!
  openToJobOffers: Boolean!
}

type Query {
  """Get info about current pyconar sponsors"""
  sponsors: [Sponsor!]!

  """Find people that match the given filters"""
  findPeople(filter: PeopleFilter!): [Person!]!

  """Find people interested in the given technology"""
  findPeopleInterestedIn(interest: String!): [Person!]!

  """Find who is open to receive job offers"""
  findPeopleOpenToHiring: [Person!]!

  """Find who is hiring and for what jobs"""
  findOpenPositions: [OpenPosition!]!

  """Talks ocurring on PyconAr `2020`"""
  nextTalks: [Talk!]!

  """All talks from `2018`, `2019` and `2020`"""
  allTalks: [Talk!]!

  """Talks given on specified `year`. One of `[2018, 2019, 2020]`"""
  talksByYear(year: String!): [Talk!]!
}

enum Seniority {
  SENIOR
  SEMI_SENIOR
  JUNIOR
}

type Speaker implements Person {
  name: String!
  email: String!
  interests: [String!]!
  openToJobOffers: Boolean!
  job: String!
  bio: String!
  talk: Talk
}

type Sponsor {
  company: Company!
  category: SponsorType!
}

enum SponsorType {
  DIAMANTE
  ORO
  PLATA
  BRONCE
}

type Talk {
  name: String!
  topic: Topic!
  description: String!
  year: String!
  speaker: Speaker!
}

enum Topic {
  PYTHON
  REST
  DIVERSITY
}

type Visitor implements Person {
  name: String!
  email: String!
  interests: [String!]!
  openToJobOffers: Boolean!
  resumeLink: String!
  githubProfile: String!
}